# Generated by Django 5.0.4 on 2024-04-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=64)),
                ('muscle_group', models.CharField(max_length=64)),
                ('technique_description', models.CharField(max_length=256)),
            ],
        ),
    ]
