# Generated by Django 5.0.4 on 2024-04-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfitworkout', '0003_exerciseintraining_training_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='uid',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exerciseintraining',
            name='uid',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
