# Generated by Django 5.0.4 on 2024-04-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfitworkout', '0004_exercise_uid_exerciseintraining_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='uid',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
