# Generated by Django 5.0.4 on 2024-04-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfitworkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='technique_description',
            field=models.CharField(max_length=512),
        ),
    ]
